// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euvgokdrwboojqbngoqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1dmdva2Ryd2Jvb2pxYm5nb3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjE4MjMsImV4cCI6MjA3MDk5NzgyM30.zdgcI1D4rsXftGXPmtOPF5X7cX2rk-X3in2FLrpUoYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});